version: "3.9"

services:
  app:
    image: traefik/whoami
    container_name: whoami
    environment:
      - DOMAIN={{DOMAIN}}              
      - ALLOWED_IPS={{ALLOWED_IPS}}   

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

      - "traefik.http.services.whoami.loadbalancer.server.port=80"

      - "traefik.http.routers.whoami.middlewares=${ALLOWED_IPS:+ipfilter@file}"

    networks:
      - traefik

networks:
  traefik:
    external: true
